[package]
name = "proc-db-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"
dotenvy = "0.15"
sqlx = {version="0.7.4", features=["mysql", "runtime-tokio"]}
tokio = { version = "1", features = ["full"] }
chrono = "0.4.37"